-- db/01_schema.sql
-- Final relational schema normalized to Fourth Normal Form (4NF)
-- Based on NORMALIZATION_4FN.xlsx and Exercise 02 requirements.
--
-- Run once against library_db as the database owner / PostgreSQL administrator:
--   psql -U postgres -d library_db -f db/01_schema.sql
--
-- Design rule for ON UPDATE:
-- Surrogate identifiers are treated as immutable, so no ON UPDATE action is declared.
-- PostgreSQL therefore uses its default NO ACTION behavior for updates to referenced keys.

\set ON_ERROR_STOP on

BEGIN;

-- ---------------------------------------------------------------------------
-- FORMATS
-- PK: format_id uniquely identifies each format independently of its name.
-- UNIQUE: name prevents duplicate catalog entries.
-- CHECK: catalog names cannot be empty.
-- ---------------------------------------------------------------------------
CREATE TABLE formats (
    format_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(120) NOT NULL,

    CONSTRAINT pk_formats PRIMARY KEY (format_id),
    CONSTRAINT uq_formats_name UNIQUE (name),
    CONSTRAINT chk_formats_name_not_blank CHECK (btrim(name) <> '')
);

-- ---------------------------------------------------------------------------
-- CATEGORIES
-- PK: category_id uniquely identifies each category.
-- UNIQUE: name prevents duplicate catalog entries.
-- CHECK: category names cannot be empty.
-- ---------------------------------------------------------------------------
CREATE TABLE categories (
    category_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(120) NOT NULL,

    CONSTRAINT pk_categories PRIMARY KEY (category_id),
    CONSTRAINT uq_categories_name UNIQUE (name),
    CONSTRAINT chk_categories_name_not_blank CHECK (btrim(name) <> '')
);

-- ---------------------------------------------------------------------------
-- AUTHORS
-- PK: author_id is used instead of author name because different real authors
-- may legitimately share the same name.
-- CHECK: author name cannot be empty.
-- ---------------------------------------------------------------------------
CREATE TABLE authors (
    author_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(160) NOT NULL,

    CONSTRAINT pk_authors PRIMARY KEY (author_id),
    CONSTRAINT chk_authors_name_not_blank CHECK (btrim(name) <> '')
);

-- ---------------------------------------------------------------------------
-- GENRES
-- PK: genre_id uniquely identifies each genre.
-- UNIQUE: name prevents duplicate genre catalog entries.
-- CHECK: genre name cannot be empty.
-- ---------------------------------------------------------------------------
CREATE TABLE genres (
    genre_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(120) NOT NULL,

    CONSTRAINT pk_genres PRIMARY KEY (genre_id),
    CONSTRAINT uq_genres_name UNIQUE (name),
    CONSTRAINT chk_genres_name_not_blank CHECK (btrim(name) <> '')
);

-- ---------------------------------------------------------------------------
-- CONCEPTS
-- PK: concept_id uniquely identifies a reusable concept.
-- UNIQUE: concept name is unique in the reusable concept catalog.
-- IMPORTANT: definition is NOT stored here because the definition belongs to
-- the BOOK_CONCEPTS relationship and may differ from one book to another.
-- ---------------------------------------------------------------------------
CREATE TABLE concepts (
    concept_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(160) NOT NULL,

    CONSTRAINT pk_concepts PRIMARY KEY (concept_id),
    CONSTRAINT uq_concepts_name UNIQUE (name),
    CONSTRAINT chk_concepts_name_not_blank CHECK (btrim(name) <> '')
);

-- ---------------------------------------------------------------------------
-- USERS
-- PK: user_id uniquely identifies a registered user.
-- UNIQUE: email is the login identifier and cannot be duplicated.
-- CHECK: only USER and ADMIN roles are valid.
-- A partial UNIQUE index created later guarantees at most one ADMIN.
-- ---------------------------------------------------------------------------
CREATE TABLE users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    email VARCHAR(254) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(10) NOT NULL DEFAULT 'USER',

    CONSTRAINT pk_users PRIMARY KEY (user_id),
    CONSTRAINT uq_users_email UNIQUE (email),
    CONSTRAINT chk_users_email_not_blank CHECK (btrim(email) <> ''),
    CONSTRAINT chk_users_password_hash_not_blank CHECK (btrim(password_hash) <> ''),
    CONSTRAINT chk_users_role CHECK (role IN ('USER', 'ADMIN'))
);

-- Database-level defense for RF-20: at most one Administrator can exist.
CREATE UNIQUE INDEX uq_users_single_admin
    ON users (role)
    WHERE role = 'ADMIN';

-- ---------------------------------------------------------------------------
-- BOOKS
-- PK: book_id is the internal surrogate identifier.
-- Candidate key / UNIQUE: ISBN identifies a book for searches and must not repeat.
-- FK: format_id and category_id reference independent catalogs.
-- ON DELETE RESTRICT: a referenced format/category cannot be deleted while books
-- still use it, preventing accidental catalog damage.
-- CHECK: title/ISBN cannot be blank; stock and price cannot be negative.
-- ---------------------------------------------------------------------------
CREATE TABLE books (
    book_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    isbn VARCHAR(20) NOT NULL,
    title VARCHAR(255) NOT NULL,
    publication_year SMALLINT NOT NULL,
    price NUMERIC(10,2) NOT NULL,
    stock INTEGER NOT NULL DEFAULT 0,
    format_id BIGINT NOT NULL,
    category_id BIGINT NOT NULL,

    CONSTRAINT pk_books PRIMARY KEY (book_id),
    CONSTRAINT uq_books_isbn UNIQUE (isbn),
    CONSTRAINT chk_books_isbn_not_blank CHECK (btrim(isbn) <> ''),
    CONSTRAINT chk_books_title_not_blank CHECK (btrim(title) <> ''),
    CONSTRAINT chk_books_publication_year CHECK (publication_year BETWEEN 1 AND 9999),
    CONSTRAINT chk_books_price_nonnegative CHECK (price >= 0),
    CONSTRAINT chk_books_stock_nonnegative CHECK (stock >= 0),

    CONSTRAINT fk_books_format
        FOREIGN KEY (format_id)
        REFERENCES formats (format_id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_books_category
        FOREIGN KEY (category_id)
        REFERENCES categories (category_id)
        ON DELETE RESTRICT
);

-- Search / FK support indexes.
-- ISBN already has a UNIQUE B-tree index through uq_books_isbn.
CREATE INDEX idx_books_title_lower ON books (lower(title));
CREATE INDEX idx_books_format_id ON books (format_id);
CREATE INDEX idx_books_category_id ON books (category_id);

-- ---------------------------------------------------------------------------
-- BOOK_AUTHORS
-- 4NF bridge for the independent multivalued dependency Book ->> Author.
-- Composite PK prevents the same author from being linked twice to the same book.
-- ON DELETE CASCADE from BOOKS removes only relationship rows when a book is deleted.
-- ON DELETE RESTRICT from AUTHORS protects an author that is still referenced.
-- ---------------------------------------------------------------------------
CREATE TABLE book_authors (
    book_id BIGINT NOT NULL,
    author_id BIGINT NOT NULL,

    CONSTRAINT pk_book_authors PRIMARY KEY (book_id, author_id),

    CONSTRAINT fk_book_authors_book
        FOREIGN KEY (book_id)
        REFERENCES books (book_id)
        ON DELETE CASCADE,

    CONSTRAINT fk_book_authors_author
        FOREIGN KEY (author_id)
        REFERENCES authors (author_id)
        ON DELETE RESTRICT
);

CREATE INDEX idx_book_authors_author_id ON book_authors (author_id);

-- ---------------------------------------------------------------------------
-- BOOK_GENRES
-- 4NF bridge for the independent multivalued dependency Book ->> Genre.
-- Composite PK prevents duplicate book-genre associations.
-- ---------------------------------------------------------------------------
CREATE TABLE book_genres (
    book_id BIGINT NOT NULL,
    genre_id BIGINT NOT NULL,

    CONSTRAINT pk_book_genres PRIMARY KEY (book_id, genre_id),

    CONSTRAINT fk_book_genres_book
        FOREIGN KEY (book_id)
        REFERENCES books (book_id)
        ON DELETE CASCADE,

    CONSTRAINT fk_book_genres_genre
        FOREIGN KEY (genre_id)
        REFERENCES genres (genre_id)
        ON DELETE RESTRICT
);

CREATE INDEX idx_book_genres_genre_id ON book_genres (genre_id);

-- ---------------------------------------------------------------------------
-- BOOK_CONCEPTS
-- 4NF relationship between books and reusable concepts.
-- The definition, chapter and page belong to the (book_id, concept_id) pair.
-- Composite PK guarantees one definition record per concept within a book.
-- ---------------------------------------------------------------------------
CREATE TABLE book_concepts (
    book_id BIGINT NOT NULL,
    concept_id BIGINT NOT NULL,
    definition TEXT NOT NULL,
    chapter_reference VARCHAR(120),
    page_reference VARCHAR(50),

    CONSTRAINT pk_book_concepts PRIMARY KEY (book_id, concept_id),
    CONSTRAINT chk_book_concepts_definition_not_blank CHECK (btrim(definition) <> ''),

    CONSTRAINT fk_book_concepts_book
        FOREIGN KEY (book_id)
        REFERENCES books (book_id)
        ON DELETE CASCADE,

    CONSTRAINT fk_book_concepts_concept
        FOREIGN KEY (concept_id)
        REFERENCES concepts (concept_id)
        ON DELETE RESTRICT
);

CREATE INDEX idx_book_concepts_concept_id ON book_concepts (concept_id);

-- ---------------------------------------------------------------------------
-- BOOK_IMAGES
-- One book may have many image metadata rows.
-- Files remain in the filesystem; PostgreSQL stores their metadata/reference.
-- ON DELETE CASCADE removes image metadata when its parent book is deleted.
-- CHECK: supported MIME types are JPG/JPEG, PNG and WebP; file size must be > 0.
-- UNIQUE file_path prevents two metadata rows from pointing to the same stored file.
-- A partial UNIQUE index created later allows at most one cover per book.
-- ---------------------------------------------------------------------------
CREATE TABLE book_images (
    image_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    book_id BIGINT NOT NULL,
    file_name VARCHAR(255) NOT NULL,
    file_path VARCHAR(500) NOT NULL,
    mime_type VARCHAR(50) NOT NULL,
    file_size_bytes BIGINT NOT NULL,
    alt_text VARCHAR(500) NOT NULL,
    is_cover BOOLEAN NOT NULL DEFAULT FALSE,

    CONSTRAINT pk_book_images PRIMARY KEY (image_id),
    CONSTRAINT uq_book_images_file_path UNIQUE (file_path),
    CONSTRAINT chk_book_images_file_name_not_blank CHECK (btrim(file_name) <> ''),
    CONSTRAINT chk_book_images_file_path_not_blank CHECK (btrim(file_path) <> ''),
    CONSTRAINT chk_book_images_mime_type CHECK (
        mime_type IN ('image/jpeg', 'image/png', 'image/webp')
    ),
    CONSTRAINT chk_book_images_file_size_positive CHECK (file_size_bytes > 0),
    CONSTRAINT chk_book_images_alt_text_not_blank CHECK (btrim(alt_text) <> ''),

    CONSTRAINT fk_book_images_book
        FOREIGN KEY (book_id)
        REFERENCES books (book_id)
        ON DELETE CASCADE
);

CREATE INDEX idx_book_images_book_id ON book_images (book_id);

-- At most one active cover image per book.
CREATE UNIQUE INDEX uq_book_images_one_cover_per_book
    ON book_images (book_id)
    WHERE is_cover = TRUE;

-- ---------------------------------------------------------------------------
-- Minimum privileges for the Node.js application role.
-- The application can perform CRUD but cannot create/drop schema objects.
-- ---------------------------------------------------------------------------
REVOKE CREATE ON SCHEMA public FROM PUBLIC;
GRANT USAGE ON SCHEMA public TO library_app;

GRANT SELECT, INSERT, UPDATE, DELETE
ON ALL TABLES IN SCHEMA public
TO library_app;

GRANT USAGE, SELECT
ON ALL SEQUENCES IN SCHEMA public
TO library_app;

-- Apply the same privileges to future tables/sequences created by this owner.
ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO library_app;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT USAGE, SELECT ON SEQUENCES TO library_app;

COMMIT;

-- ===========================================================================
-- POINT 8 - NEGATIVE INTEGRITY TESTS
-- Run these manually AFTER db/02_seed_30_per_table.sql.
-- Keep each statement, expected result, and the real PostgreSQL error screenshot.
-- They are intentionally commented so this schema file can complete successfully.
-- ===========================================================================

-- TEST N1 - Duplicate ISBN
-- Expected: rejected by uq_books_isbn.
-- INSERT INTO books
--     (isbn, title, publication_year, price, stock, format_id, category_id)
-- VALUES
--     ('978-1-4028-9462-6', 'Duplicate ISBN Test', 2026, 10.00, 1, 1, 1);

-- TEST N2 - Negative stock
-- Expected: rejected by chk_books_stock_nonnegative.
-- INSERT INTO books
--     (isbn, title, publication_year, price, stock, format_id, category_id)
-- VALUES
--     ('9780000000991', 'Negative Stock Test', 2026, 10.00, -1, 1, 1);

-- TEST N3 - Invalid / negative price
-- Expected: rejected by chk_books_price_nonnegative.
-- INSERT INTO books
--     (isbn, title, publication_year, price, stock, format_id, category_id)
-- VALUES
--     ('9780000000992', 'Negative Price Test', 2026, -0.01, 1, 1, 1);

-- TEST N4 - Nonexistent foreign key
-- Expected: rejected by fk_books_format.
-- INSERT INTO books
--     (isbn, title, publication_year, price, stock, format_id, category_id)
-- VALUES
--     ('9780000000993', 'Missing FK Test', 2026, 10.00, 1, 999999, 1);

-- TEST N5 - Delete a referenced author
-- Expected: rejected by fk_book_authors_author because ON DELETE RESTRICT is used.
-- DELETE FROM authors WHERE author_id = 1;

-- TEST N6 - Create a second Administrator
-- Expected: rejected by partial UNIQUE index uq_users_single_admin.
-- INSERT INTO users (email, password_hash, role)
-- VALUES (
--     'second.admin@example.edu',
--     '$2b$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy',
--     'ADMIN'
-- );
