-- db/05_triggers.sql
-- Triggers for Exercise 02.
-- Run once against library_db as the database owner / PostgreSQL administrator,
-- AFTER db/04_stored_procedures.sql:
--
--   psql -U postgres -d library_db -f db/05_triggers.sql

\set ON_ERROR_STOP on

BEGIN;

-- ===========================================================================
-- TRIGGER 1 - Automatic single cover image per book (RF-16)
-- REQUIREMENTS.md states: "Al marcar una nueva imagen como portada, la
-- imagen previamente marcada deja de ser portada automáticamente."
-- The partial UNIQUE index (uq_book_images_one_cover_per_book, in
-- db/01_schema.sql) only BLOCKS a second TRUE value; it cannot toggle the
-- previous cover off by itself. This trigger provides the automatic
-- behavior the requirement asks for.
-- ===========================================================================
CREATE OR REPLACE FUNCTION trg_fn_book_images_single_cover()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.is_cover THEN
        UPDATE book_images
        SET is_cover = FALSE
        WHERE book_id = NEW.book_id
          AND image_id <> NEW.image_id
          AND is_cover = TRUE;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_book_images_single_cover
BEFORE INSERT OR UPDATE OF is_cover, book_id ON book_images
FOR EACH ROW
EXECUTE FUNCTION trg_fn_book_images_single_cover();

-- ===========================================================================
-- TRIGGER 2 - Defense-in-depth for single Administrator (RF-20, RNF-06)
-- The partial UNIQUE index uq_users_single_admin already blocks a second
-- ADMIN at the database level. This trigger adds a second, independent
-- layer that also raises a clear, application-friendly error message.
-- ===========================================================================
CREATE OR REPLACE FUNCTION trg_fn_users_single_admin()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.role = 'ADMIN' THEN
        IF EXISTS (
            SELECT 1
            FROM users
            WHERE role = 'ADMIN'
              AND user_id <> COALESCE(NEW.user_id, -1)
        ) THEN
            RAISE EXCEPTION
                'Ya existe un usuario con rol ADMIN. Solo se permite un Administrador (RF-20).'
                USING ERRCODE = 'unique_violation';
        END IF;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_users_single_admin
BEFORE INSERT OR UPDATE OF role ON users
FOR EACH ROW
EXECUTE FUNCTION trg_fn_users_single_admin();

-- ===========================================================================
-- TRIGGER 3 - Audit trail for price/stock changes (RNF-10, RF-18, RF-19)
-- Keeps a history of every price or stock change on a book without
-- requiring any change to services/libroService.js.
-- ===========================================================================
CREATE TABLE book_price_stock_audit (
    audit_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    book_id BIGINT NOT NULL,
    changed_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    old_price NUMERIC(10,2),
    new_price NUMERIC(10,2),
    old_stock INTEGER,
    new_stock INTEGER,

    CONSTRAINT pk_book_price_stock_audit PRIMARY KEY (audit_id),
    CONSTRAINT fk_book_price_stock_audit_book
        FOREIGN KEY (book_id)
        REFERENCES books (book_id)
        ON DELETE CASCADE
);

CREATE OR REPLACE FUNCTION trg_fn_books_audit_price_stock()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.price IS DISTINCT FROM OLD.price OR NEW.stock IS DISTINCT FROM OLD.stock THEN
        INSERT INTO book_price_stock_audit (book_id, old_price, new_price, old_stock, new_stock)
        VALUES (OLD.book_id, OLD.price, NEW.price, OLD.stock, NEW.stock);
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_books_audit_price_stock
AFTER UPDATE OF price, stock ON books
FOR EACH ROW
EXECUTE FUNCTION trg_fn_books_audit_price_stock();

-- ===========================================================================
-- Minimum privileges for the Node.js application role (RNF-13).
-- ===========================================================================
GRANT SELECT, INSERT, UPDATE, DELETE ON book_price_stock_audit TO library_app;
GRANT USAGE, SELECT ON SEQUENCE book_price_stock_audit_audit_id_seq TO library_app;

COMMIT;

\echo '3 triggers (and their functions) created successfully.'
